### ISSUE TITLE
Run Database locally instead of MongoDB

### ISSUE THREAD

**Issue by A-Pandya** [masterminnich/BadgingSystem#2]
One major issue with using a service like Mongo DB is using a third party to store student credential information which possesses a security concern for the institution involved

A preferred solution would be to be able to run the database locally instead of connecting to a "cloud" based database

.

**Comment by masterminnich** [comment]
Atlas, MongoDB’s fully managed service, is recommended in the README for ease of use. You raise a valid concern about third-party storage and student information. Luckily you can self-host the data storage using [MongoDB Community Edition](https://www.mongodb.com/docs/manual/administration/install-community/). 

The README has needed an overhaul for a while. The next release should include the following steps for those wishing to self-host the database.

1. Install MongoDB Community Edition
2. Start the server `mongod`
3. Enter the shell `mongosh`
4. Within the mongo shell, create a database named eyra `use eyra`
5. Still inside mongo shell... create a database user `db.createUser({
user: “admin”,
pwd: “password”,
roles:[“readWrite”,”dbAdmin”]
})`
7. Navigate to the directory where Eyra is installed. Connect Eyra to MongoDB `node setup.js mongodb://admin:password@localhost:27017/eyra`
